### PR TITLE
R&D - Сode Standard

### PR DESCRIPTION
**Pull request by gHashTag**

### CODE REVIEW

**Comment by vivalaakam** [comment]
disagree about default exports

**Comment by gHashTag** [comment]
> disagree about default exports

Why?

**Comment by vivalaakam** [comment]
Ease of use, because many IDEs are good at importing components by name, there will also be no discrepancies that the component is called in the original one way, and in another import it is easier to refactor the code

**Review by vivalaakam — COMMENTED** [review]
remove from text all export default and hide point about sag icons (we need normal tests for it)

**Review by vivalaakam — APPROVED** [review]

**Pull request merged**
