### PR TITLE
refactor(LedgerFinish): code

### PR DESCRIPTION
**Pull request by Crazy-MIXER**
- Change the imports to absolute
- Replace navigation hook
- Move text to i18n
- Transferring the screen logic to components
- Add `i18n `& `i18params `to `finish `component

### CODE REVIEW

**Review by gHashTag — APPROVED** [review]

**Comment by Crazy-MIXER** [comment]
return the finish screen on the `LedgerScreen`

**Review by gHashTag — APPROVED** [review]

**Review by vivalaakam — APPROVED** [review]

**Review by vivalaakam — CHANGES_REQUESTED** [review]
resolve conflicts pls

**Comment by Crazy-MIXER** [comment]
wait correction in src/i18n.ts to correctly resolve conflicts

**Review by vivalaakam — APPROVED** [review]

**Review by vivalaakam — CHANGES_REQUESTED** [review]
fix conflicts pls

**Review by vivalaakam — APPROVED** [review]

**Pull request merged**
